service: humanizeai-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128  # Free tier optimized - up to 3.2M seconds/month
  timeout: 29      # Under 30s to stay in free tier
  environment:
    NODE_ENV: production
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
      Resource: 
        - "arn:aws:ssm:${self:provider.region}:*:parameter/humanizeai/*"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: 
              - https://www.nikola-apps.com
              - https://nikola-apps.com
              - http://localhost:5173
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: 
              - https://www.nikola-apps.com
              - https://nikola-apps.com
              - http://localhost:5173
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-aws-alerts  # Free CloudWatch monitoring

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  
  customDomain:
    domainName: api.nikola-apps.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.nikola-apps.com'
    hostedZoneId: # Will be auto-detected from Route 53
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest

resources:
  Resources:
    # API Gateway Custom Domain
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}
        Description: HumanizeAI Backend API
        
    # CloudWatch Log Group
    ApiLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-api
        RetentionInDays: 14

package:
  exclude:
    - node_modules/**
    - src/**
    - .env
    - .env.*
    - '*.test.js'
    - '*.spec.js'
    - coverage/**
    - .nyc_output/**
